### PR TITLE
Fix log typo

### LINKED ISSUE #66: Log typo when commands `?!mod rem [username]` and `?!admin rem [username]` are used
**Describe the bug**
When logs have been enabled and set to a specific channel, when either of these commands are used, `?!admin rem [username]` or `?!mod rem [username]`, instead of saying "removed *from* admins" in the logs, it says "removed *to* admins".

**To Reproduce**
1. Remove a user from the admins or mod rank: `?!admin rem [username]` or `?!mod rem [username]`
2. Watch the output in the log channel

**Screen Shots**
Screen Shot 2020-03-06 at 11 51 14 PM

**Setup (please complete the following information):**
 - Node.js Version: 13.x
 - MongoDB Version: 4.2.x
 - Release Version: 1.2.8

### PR DESCRIPTION
**Pull request by geniusjam**
Fixes #66

### CODE REVIEW

File: src/database/logger.ts [hunk 1]
```diff
@@ -101,7 +101,7 @@ export class Logger {
         var rankName = rank.charAt(0).toUpperCase() + rank.slice(1);
         var embed: any = {
             "embed": {
-                "description": `${role ? 'Role ' + role.toString() : 'User' + user.toString()} was ${type ? 'removed' : 'added'} to ${rank} rank by ${mod.toString()}`,
+                "description": `${role ? 'Role ' + role.toString() : 'User' + user.toString()} was ${type ? 'removed' : 'added to'} ${rank} rank by ${mod.toString()}`,
```
Comment (Jet132) [inline src/database/logger.ts:104]: If a user or role gets removed it will say `User Username was removed rank by SomeMod`. There should also be a `from`

Comment (geniusjam) [reply src/database/logger.ts]: Fixed!
